### ISSUE TITLE
Port D2L.Security.OAuth2 to .NET core

### ISSUE THREAD

**Issue by j3parker** [Brightspace/D2L.Security.OAuth2#6]
- [x] Remove `System.Web.HttpMessage` overloads
- [x] Switch from other serialization stuff to `Newtonsoft.Json`
- [x] Switch from `System.Runtime.Caching` to `Microsoft.Framework.Caching.Memory` for `MemoryCache` (possible breaking API changes?)
- [x] The type or namespace name `AsymmetricSignature(De)formatter` could not be found [OS: #36]
- [x] Possible `SecurityKey`/`SecurityToken` breaking API changes [OS: #36]
- [x] Where are `JwtSecurityToken` and `JwtSecurityTokenHandler`
- [x] `D2LSecurityToken` does not implement inherited abstract member `SecurityToken.SigningKey.get` [OS: #36]
- [x] Bring in DNX version of `D2L.Services.Core.Extensions`.
- [x] Build/bring in DNX version of `D2L.Services.Core.Exceptions`
- [ ] Figure out Newtonsoft.Json
- [x] Netstandard D2L.CodeStyle.Annotations (https://github.com/Brightspace/D2L.CodeStyle/pull/457) [OS: https://github.com/Brightspace/D2L.Security.OAuth2/pull/109]
